import React,{useCallback,useEffect,useRef,useState,Component} from 'react';
import {createRoot} from 'react-dom/client';
import Scene from './Scene';
import {recordWav} from './audio';
import type {Language,Reply,Shift} from '../shared/types';
import type {Departure} from '../shared/movement';
import './style.css';

async function api<T>(path:string,body?:unknown):Promise<T>{
  const response=await fetch('/api'+path,{method:body===undefined?'GET':'POST',headers:{'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});
  const data=await response.json();if(!response.ok)throw new Error(data.error||'Connection failed');return data;
}
const words={en:{start:'Start the night shift',continue:'Take your post',brief:'A note from the night watch',chapter:'THE NIGHT WATCH',tag:'Know your neighbors. Trust your instincts.',ask:'Ask the visitor anything…',send:'Ask',mic:'Speak',stop:'Stop recording',thinking:'The visitor is thinking…',inspect:'Inspect ID',register:'Resident register',history:'Conversation',admit:'Open gate',reject:'Sound alarm',ready:'Your shift begins at midnight.',settings:'Settings',close:'Close',language:'Language',connected:'Apertus connected',disconnected:'Apertus needs a connection',win:'SHIFT COMPLETE',lose:'THE VILLAGE IS NOT SAFE',retry:'Another night',menu:'Main menu',score:'Score',mistakes:'Mistakes',visitor:'Visitor',you:'You',back:'Back to the gate',loading:'A visitor is approaching…',recording:'Listening — stop to review your words',transcribing:'Transcribing with Apertus…',note:"An anomaly slipped into our neighborhood. Tonight, you're on the gate. Check each ID. Ask where they live. Look carefully before you let anyone through.",note2:'The familiar faces are not always who they seem. Ask a visitor to turn around or jump if something feels wrong. Watch how they move.',sign:'Stay sharp.',ps:'P.S. The house at Block A, No. 3 is empty. Nobody should be living there.'},
de:{start:'Nachtschicht beginnen',continue:'Zum Wachposten',brief:'Eine Nachricht von der Nachtwache',chapter:'DIE NACHTWACHE',tag:'Kenne deine Nachbarn. Vertraue deinem Instinkt.',ask:'Stelle dem Besucher eine Frage…',send:'Fragen',mic:'Sprechen',stop:'Aufnahme stoppen',thinking:'Der Besucher denkt nach…',inspect:'Ausweis prüfen',register:'Bewohnerverzeichnis',history:'Gespräch',admit:'Tor öffnen',reject:'Alarm auslösen',ready:'Deine Schicht beginnt um Mitternacht.',settings:'Einstellungen',close:'Schließen',language:'Sprache',connected:'Apertus verbunden',disconnected:'Apertus benötigt eine Verbindung',win:'SCHICHT BEENDET',lose:'DAS DORF IST NICHT SICHER',retry:'Noch eine Nacht',menu:'Hauptmenü',score:'Punkte',mistakes:'Fehler',visitor:'Besucher',you:'Du',back:'Zurück zum Tor',loading:'Ein Besucher nähert sich…',recording:'Aufnahme läuft — stoppen und Text prüfen',transcribing:'Apertus transkribiert…',note:'Eine weitere Anomalie ist in unser Dorf gelangt. Heute Nacht bewachst du das Tor. Prüfe die Ausweise. Frage nach der Adresse. Sieh genau hin, bevor du jemanden hereinlässt.',note2:'Vertraute Gesichter sind nicht immer das, was sie scheinen. Bitte einen Besucher, sich umzudrehen oder zu springen. Beobachte seine Bewegungen.',sign:'Bleib wachsam.',ps:'P.S. Das Haus in Block A, Nr. 3 steht leer. Dort sollte niemand wohnen.'}};
class RenderBoundary extends Component<{children:React.ReactNode},{error:boolean}>{state={error:false};static getDerivedStateFromError(){return{error:true};}render(){return this.state.error?<div className="render-error">The village could not load. Please reload the page and check WebGL support.</div>:this.props.children;}}
function App(){
  const [viewReset,setViewReset]=useState(0);
  const [language,setLanguage]=useState<Language>('en');const w=words[language];
  const [screen,setScreen]=useState<'title'|'brief'|'game'|'result'>('title');const [modal,setModal]=useState('');
  const [shift,setShift]=useState<Shift|null>(null);const [reply,setReply]=useState<Reply|null>(null);const [question,setQuestion]=useState('');
  const [history,setHistory]=useState<{role:string;text:string}[]>([]);const [busy,setBusy]=useState(false);const [animating,setAnimating]=useState(false);const [ready,setReady]=useState(false);const [departure,setDeparture]=useState<Departure>(null);
  const departureResolver=useRef<(()=>void)|null>(null);
  const onDeparted=useCallback(()=>{departureResolver.current?.();departureResolver.current=null;},[]);
  const [error,setError]=useState('');const [configured,setConfigured]=useState(false);const [recording,setRecording]=useState(false);const [transcribing,setTranscribing]=useState(false);
  const [register,setRegister]=useState<{name:string;address:string;occupation:string}[]>([]);const stopRecord=useRef<null|(()=>Promise<string>)>(null);const recordingTimer=useRef<ReturnType<typeof setTimeout>|null>(null);const generation=useRef(0);const operation=useRef(false);
  useEffect(()=>{api<{configured:boolean}>('/health').then(v=>setConfigured(v.configured)).catch(()=>setError('Could not connect to the game server.'));api<typeof register>('/register').then(setRegister).catch(()=>{});},[]);
  useEffect(()=>{document.documentElement.lang=language;},[language]);
  const onDone=useCallback(()=>setAnimating(false),[]);const onReady=useCallback(()=>setReady(true),[]);
  const locked=busy||animating||departure!==null||!ready||recording||transcribing;
  async function start(){if(operation.current)return;operation.current=true;setBusy(true);setError('');generation.current++;
    try{const s=await api<Shift>('/shifts',{});setShift(s);setReply(null);setHistory([]);setQuestion('');setReady(false);setAnimating(false);setDeparture(null);setScreen('game');setModal('');}catch(e){setError((e as Error).message);}finally{setBusy(false);operation.current=false;}}
  async function ask(){if(!shift?.visitor||locked||!question.trim()||operation.current)return;operation.current=true;const g=generation.current;const text=question.trim();setQuestion('');setBusy(true);setError('');setHistory(h=>[...h,{role:'user',text}]);
    try{const r=await api<Reply>(`/shifts/${shift.id}/dialogue`,{text,language,encounterId:shift.visitor.id});if(g!==generation.current)return;setReply(r);setHistory(h=>[...h,{role:'assistant',text:r.speech}]);setAnimating(r.action!=='none');}
    catch(e){setError((e as Error).message);setQuestion(text);}finally{setBusy(false);operation.current=false;}}
  async function decision(admit:boolean){if(screen!=='game'||locked||operation.current||!shift?.visitor)return;operation.current=true;setBusy(true);setError('');
    try{const result=await api<{shift:Shift;correct:boolean}>(`/shifts/${shift.id}/decision`,{admit,encounterId:shift.visitor.id});await new Promise<void>(resolve=>{departureResolver.current=resolve;setDeparture(admit?'admit':'reject');});generation.current++;setShift(result.shift);setReply(null);setHistory([]);setQuestion('');setReady(false);setDeparture(null);if(result.shift.over)setScreen('result');}
    catch(e){setError((e as Error).message);}finally{setBusy(false);operation.current=false;}}
  async function finishRecording(){const stop=stopRecord.current;if(!stop)return;stopRecord.current=null;if(recordingTimer.current)clearTimeout(recordingTimer.current);setRecording(false);setTranscribing(true);const g=generation.current;
    try{const audio=await stop();const result=await api<{text:string}>('/transcribe',{audio,language});if(g===generation.current)setQuestion(result.text);}catch(e){setError(`${(e as Error).message} ${language==='de'?'Du kannst deine Frage eintippen.':'You can type your question instead.'}`);}finally{setTranscribing(false);}}
  async function mic(){if(recording){await finishRecording();return;}if(locked)return;setError('');try{stopRecord.current=await recordWav();setRecording(true);recordingTimer.current=setTimeout(()=>void finishRecording(),15000);}catch{setError(language==='de'?'Mikrofon nicht verfügbar. Prüfe die Berechtigung oder tippe deine Frage.':'Microphone unavailable. Check permission or type your question.');}}
  function menu(){generation.current++;setScreen('title');setModal('');setShift(null);setReply(null);setError('');}
  return <main>
    <div className="scene"><RenderBoundary><Scene visitor={screen==='game'?shift?.visitor||null:null} reply={reply} departure={departure} playing={screen==='game'} viewReset={viewReset} onDone={onDone} onReady={onReady} onDeparted={onDeparted} onDecision={decision}/></RenderBoundary></div>
    <div className="vignette"/>
    <header><a className="wordmark" href="#" onClick={e=>e.preventDefault()}>KAMPUNG SAMBAU <span>OF THE DARK</span></a><button className="settings" onClick={()=>setModal('settings')} aria-label={w.settings}>⚙ <span>{language==='en'?'EN':'DE'}</span></button></header>
    {screen==='title'&&<section className="title-screen"><div className="eyebrow">AN APERTUS-POWERED MYSTERY</div><img className="title-art" src="/assets/ui/title.png" alt="Kampung Sambau — Of the Dark"/><p className="tagline">{w.tag}</p><button className="frame-button" onClick={()=>setScreen('brief')}>{w.start}<span>→</span></button><div className="title-meta"><span>01 / NIGHT SHIFT</span><span>ENGLISH · DEUTSCH</span></div></section>}
    {screen==='brief'&&<section className="brief-screen"><article className="paper"><div className="eyebrow">{w.chapter} / 001</div><h1>{w.brief}</h1><p>{w.note}</p><p>{w.note2}</p><p className="signature">{w.sign}</p><p className="postscript">{w.ps}</p></article><button className="frame-button" disabled={busy} onClick={start}>{busy?'…':w.continue}<span>→</span></button></section>}
    {screen==='game'&&shift&&<><div className="shift-info"><span className="eyebrow">{w.chapter}</span><span>{w.visitor} {shift.index+1} / {shift.total}</span></div><div className="clock"><span>{shift.time}</span><small>{w.mistakes} {shift.mistakes} / 3</small></div>
      <nav className="tools"><button aria-label={language==='de'?'Ansicht zurücksetzen':'Reset view'} onClick={()=>setViewReset(n=>n+1)}>◎ <span>{language==='de'?'Ansicht zurücksetzen':'Reset view'}</span></button><button onClick={()=>setModal('id')}>▣ <span>{w.inspect}</span></button><button onClick={()=>setModal('register')}>▤ <span>{w.register}</span></button><button onClick={()=>setModal('history')}>☷ <span>{w.history}</span></button></nav>
      <section className="dialogue-dock"><div className="subtitle" aria-live="polite"><span>{busy?w.thinking:!ready?w.loading:recording?w.recording:transcribing?w.transcribing:reply?shift.visitor?.card.printedName:w.ready}</span>{reply&&!busy&&<p>{reply.speech}</p>}</div><form onSubmit={e=>{e.preventDefault();void ask();}}><button className={recording?'mic recording':'mic'} type="button" onClick={mic} disabled={!recording&&locked} aria-label={recording?w.stop:w.mic}><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6"><rect x="9" y="2" width="6" height="12" rx="3"/><path d="M5 10a7 7 0 0014 0M12 17v5M8 22h8"/></svg></button><input aria-label={w.ask} value={question} onChange={e=>setQuestion(e.target.value)} placeholder={w.ask} maxLength={2000} disabled={locked}/><button className="send" disabled={locked||!question.trim()}>{w.send} ↗</button></form><div className="decisions"><button disabled={locked} onClick={()=>decision(false)} className="reject"><i/>{w.reject}</button><span>CHECK. QUESTION. DECIDE.</span><button disabled={locked} onClick={()=>decision(true)} className="admit"><i/>{w.admit}</button></div></section></>}
    {screen==='result'&&shift&&<section className="result"><span className="eyebrow">KAMPUNG SAMBAU / {shift.time}</span><h1>{shift.won?w.win:w.lose}</h1><p>{w.score} <strong>{shift.score}</strong> <span>·</span> {w.mistakes} {shift.mistakes} / 3</p><button className="frame-button" disabled={busy} onClick={start}>{w.retry} ↻</button><button className="text-button" onClick={menu}>{w.menu}</button></section>}
    {error&&<div className="error" role="alert">{error}<button aria-label={w.close} onClick={()=>setError('')}>×</button></div>}
    {modal&&<div className="modal-backdrop" onClick={()=>setModal('')}><section className={'modal '+(modal==='id'?'id-modal':'')} role="dialog" aria-modal="true" aria-label={modal==='settings'?w.settings:modal==='register'?w.register:modal==='id'?w.inspect:w.history} onClick={e=>e.stopPropagation()}><button className="close" aria-label={w.close} onClick={()=>setModal('')}>×</button>
      {modal==='settings'&&<><div className="eyebrow">KAMPUNG SAMBAU</div><h2>{w.settings}</h2><label>{w.language}<select value={language} onChange={e=>setLanguage(e.target.value as Language)}><option value="en">English</option><option value="de">Deutsch</option></select></label><p className="connection"><i className={configured?'online':''}/>{configured?w.connected:w.disconnected}</p><p className="muted">Apertus v1.5 · 70B</p><p className="muted">{language==='de'?'Audio wird an denselben Apertus-Endpunkt gesendet. Transkription vor dem Senden prüfen.':'Audio is sent to the same Apertus endpoint. Review the transcript before sending.'}</p></>}
      {modal==='id'&&shift?.visitor&&<><div className="eyebrow">{w.inspect}</div><h2>{shift.visitor.card.printedName}</h2><img className="id-texture" src={shift.visitor.cardImage} alt={w.inspect}/><dl><dt>ID</dt><dd>{shift.visitor.card.printedIDNumber}</dd><dt>{language==='de'?'Adresse':'Address'}</dt><dd>{shift.visitor.card.printedAddress}</dd><dt>{language==='de'?'Geburtstag':'Born'}</dt><dd>{shift.visitor.card.birthDay}</dd></dl></>}
      {modal==='register'&&<><div className="eyebrow">KAMPUNG SAMBAU</div><h2>{w.register}</h2><div className="register">{register.map(r=><article key={r.name}><span>{r.address}</span><h3>{r.name}</h3><p>{r.occupation}</p></article>)}<article><span>Block A, No. 3</span><h3>{language==='de'?'Leerstehend':'Unoccupied'}</h3></article></div></>}
      {modal==='history'&&<><div className="eyebrow">{w.visitor} {shift?shift.index+1:''}</div><h2>{w.history}</h2><div className="history">{history.length===0?<p className="muted">{w.ask}</p>:history.map((m,i)=><article key={i} className={m.role}><span>{m.role==='user'?w.you:w.visitor}</span><p>{m.text}</p></article>)}</div></>}
    </section></div>}
    {screen!=='game'&&<footer><span>NIGHT WATCH PROTOCOL</span><span>BUILT WITH APERTUS <i/></span></footer>}
  </main>;
}
createRoot(document.getElementById('root')!).render(<App/>);
